# Generated by Django 3.0.3 on 2020-04-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeats_recipes', '0001_initial'),
        ('myeats_scheduler', '0002_auto_20200419_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='myeats_recipes.Recipe'),
        ),
    ]
